DROP TABLE IF EXISTS ledger_lines;
DROP TABLE IF EXISTS journal_entries;
DROP TABLE IF EXISTS accounts;
DROP TYPE IF EXISTS journal_status;
DROP TYPE IF EXISTS account_type;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
